### PR TITLE
Add Original PDF

### LINKED ISSUE #1: Add Original PDF
I think the first step is to simply add the PDF in-question to this repo:
http://webguide.ucsb.edu/media/web-accessibility-guidelines.pdf

### PR DESCRIPTION
**Pull request by loganfranken**
Fixes #1

### CODE REVIEW

**Comment by loganfranken** [comment]
Hey @cfwebmaster and @garster, anything you want me to change to get this one merged?

**Comment by UCSB-jcolo** [comment]
Nope, not on my end.. looks straightforward
thanks Logan!

**Comment by loganfranken** [comment]
Thanks @cfwebmaster! Would you be able to merge this?

**Comment by loganfranken** [comment]
Thanks @garster!

**Pull request merged**
